name: indexer-main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: volta install node
    - run: volta install yarn
    - run: yarn --frozen-lockfile
    - run: yarn lint
    - run: yarn build
